### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by nx10** [XAMPPRocky/Rustacean.app#5]
Is windows support planned? It looks like most of the functionality could translate pretty much directly to a windows status bar application.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However right now I don't intend to provide Windows support. While the current functionality might directly map to a windows status bar app, I don't think will always be the case. I also do not have a Windows machine to create or test such an app.

If someone else wants to create a `Rustacean.exe` or something that's an equivalent for Windows, please do!
